apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: backend

profiles:
  - name: local
    activation:
      - command: dev
    build:
      artifacts:
        - image: thisisommore/hh-nodejs
          sync:
            manual:
              - src: "src/**/*.ts"
                dest: .

  - name: prod
    activation:
      - command: run
    build:
      artifacts:
        - image: thisisommore/hh-nodejs

deploy:
  kubectl:
    manifests:
      - k8s/mysql-deploy.yaml
      - k8s/mysql-service.yaml
      - k8s/nodejs-deploy.yaml
      - k8s/nodejs-service.yaml
