apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        resources:
          limits:
            memory: "900M"
            cpu: "500m"
        ports:
        - containerPort: 3306
          name: mysql
        env:
          - name: MYSQL_USER
            value: Om
          - name: MYSQL_PASSWORD
            value: "0000"
          - name: MYSQL_ROOT_PASSWORD
            value: "100"
          - name: MYSQL_DATABASE
            value: helpinghands
