apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deploy
spec:
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs
          image: thisisommore/hh-nodejs

          resources:
            limits:
              memory: "1000M"
              cpu: "1000m"
          env:
            - name: MYSQL_HOST
              value: mysql-service
            - name: MYSQL_USER
              value: Om
            - name: MYSQL_PASSWORD
              value: "0000"
            - name: PORT
              value: "3000"
            - name: MAILJET_USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: mailjet-auth
            - name: MAILJET_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: pass
                  name: mailjet-auth
            - name: FIREBASE_CONFIG_PATH
              value: /hh-nodejs/firebase/helping-hands-f0a98-firebase-adminsdk-ia6nq-df53617bfe.json
          volumeMounts:
            - mountPath: /hh-nodejs/firebase
              name: firebase-config
          ports:
            - containerPort: 3000
      volumes:
        - name: firebase-config
          secret:
            secretName: firebase-config
      imagePullSecrets:
        - name: regcred
